{{- if or .Values.roundcube.customConfig .Values.roundcube.multiDomain.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "roundcube.fullname" . }}-custom
  labels:
    {{- include "roundcube.labels" . | nindent 4 }}
data:
  config.inc.php: |
{{- if .Values.roundcube.multiDomain.enabled }}
    <?php
    // Multi-domain configuration
    // This allows different settings per domain

    // Default configuration (fallback)
    $config['default_host'] = '{{ .Values.roundcube.defaultHost }}';
    $config['smtp_server'] = '{{ .Values.roundcube.smtpServer }}';
    $config['smtp_port'] = {{ .Values.roundcube.smtpPort }};
    $config['smtp_user'] = '{{ .Values.roundcube.smtpUser }}';
    $config['smtp_pass'] = '{{ .Values.roundcube.smtpPass }}';

    // Get current host
    $current_host = $_SERVER['HTTP_HOST'] ?? '';

    // Per-domain configuration
    switch($current_host) {
    {{- range .Values.roundcube.multiDomain.domains }}
        case '{{ .name }}':
        case 'www.{{ .name }}':
            // Configuration for {{ .name }}
{{ .config | indent 12 }}
            break;
    {{- end }}
        default:
            // Use default configuration
            break;
    }

    // Common settings for all domains (can be overridden above)
    if (!isset($config['smtp_user'])) {
        $config['smtp_user'] = '%u';
    }
    if (!isset($config['smtp_pass'])) {
        $config['smtp_pass'] = '%p';
    }
{{- else }}
{{ .Values.roundcube.customConfig | indent 4 }}
{{- end }}
{{- end }}