{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) (eq .Values.database.type "sqlite") -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "roundcube.fullname" . }}-sqlite
  labels:
    {{- include "roundcube.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
