{{- if and .Values.roundcube.pluginSecrets (not .Values.roundcube.pluginSecretsExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "roundcube.fullname" . }}-plugin-secrets
  labels:
    {{- include "roundcube.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.roundcube.pluginSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}