"""
MkDocs plugin to process chart README files.
This plugin automatically adjusts README content from Helm charts for better web display.
"""
import re
import os
from pathlib import Path


def on_page_markdown(markdown, page, config, files):
    """Process markdown content for chart README pages."""
    
    # Only process chart pages
    if not page.file.src_path.startswith("charts/"):
        return markdown
    
    # Remove the autogenerated helm-docs header if present
    markdown = re.sub(
        r'^# .*\n\n<!---.*helm-docs.*-->\n',
        '',
        markdown,
        flags=re.MULTILINE | re.DOTALL
    )
    
    # Fix relative links to point to GitHub
    chart_name = page.file.src_path.split('/')[1].replace('.md', '')
    github_base = f"https://github.com/encircle360-oss/helm-charts/tree/main/charts/{chart_name}"
    
    # Replace relative links with absolute GitHub links
    markdown = re.sub(
        r'\[([^\]]+)\]\((?!http)([^)]+)\)',
        rf'[\1]({github_base}/\2)',
        markdown
    )
    
    # Add installation instructions at the top if not present
    if "## Installation" not in markdown and "helm install" not in markdown:
        install_block = f"""
## Installation

```bash
helm repo add encircle360 https://encircle360-oss.github.io/helm-charts
helm repo update
helm install my-{chart_name} encircle360/{chart_name}
```

---

"""
        # Insert after the first heading
        markdown = re.sub(r'(^# [^\n]+\n)', r'\1' + install_block, markdown, count=1)
    
    # Add link to values.yaml at the end if not present
    if "values.yaml" not in markdown.lower():
        values_link = f"""

## Default Values

For a complete list of configuration options, see the [values.yaml]({github_base}/values.yaml) file.
"""
        markdown += values_link
    
    return markdown