{{- if and .Values.global.enabled .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubevirt-operator-rolebinding
  namespace: {{ include "kubevirt.namespace" . }}
  labels:
    {{- include "kubevirt.operator.labels" . | nindent 4 }}
    kubevirt.io: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubevirt-operator
subjects:
  - kind: ServiceAccount
    name: {{ include "kubevirt.operator.serviceAccountName" . }}
    namespace: {{ include "kubevirt.namespace" . }}
{{- end }}
