{{- if and .Values.global.enabled .Values.operator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubevirt.operator.serviceAccountName" . }}
  namespace: {{ include "kubevirt.namespace" . }}
  labels:
    kubevirt.io: ""
{{- with .Values.operator.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
